# This is a sample aws-auth-patch.yml file. 
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.

apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::934659256376:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-11LAOHSNZKOSZ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::934659256376:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-08T19:37:42Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1680"
  uid: 2b4a4045-111d-402b-939e-93b2cc189ace