# This is a sample aws-auth-patch.yml file. 
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.

apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::216705566066:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1DBHED9TMYRZZ
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::216705566066:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  uid: b4f9354c-1897-11ec-899b-1b9b5b2d2070
